/* ============================================================
 * NUSANTARA BUSINESS — SHELL CONTROLLER
 * Unified frontend shell + native People navigation.
 * People data remains on the separate production Absensi backend.
 * ============================================================ */
(function(){
'use strict';
const KEY='__nusantaraBusinessShell';
if(window[KEY]?.installed)return;
const state={installed:false,version:'1.3.0'};
function loadCss(){if(document.getElementById('businessShellStyle'))return;const link=document.createElement('link');link.id='businessShellStyle';link.rel='stylesheet';link.href='css/business-shell.css';document.head.appendChild(link)}
function installBrand(){const brand=document.querySelector('.sidebar .brand');if(brand){const title=brand.querySelector('.brand-title'),subtitle=brand.querySelector('.brand-subtitle'),mark=brand.querySelector('.brand-mark');if(title)title.textContent='Nusantara Business';if(subtitle)subtitle.textContent='Business Management Portal';if(mark)mark.textContent='NB';if(!brand.querySelector('.business-brand-context')){const c=document.createElement('div');c.className='business-brand-context';c.innerHTML='<span class="dot"></span><span>Unified Platform</span>';brand.appendChild(c)}}const t=document.querySelector('#loadingScreen .loading-title'),m=document.querySelector('#loadingScreen .brand-mark');if(t)t.textContent='Nusantara Business';if(m)m.textContent='NB';document.title='Nusantara Business'}
function installTopbarContext(){const left=document.querySelector('.topbar-left');if(!left||document.getElementById('businessShellContext'))return;const c=document.createElement('div');c.id='businessShellContext';c.className='business-shell-context';c.innerHTML='<span class="shell-context-dot"></span><strong>Business</strong><span>Unified Portal</span>';const a=document.querySelector('.top-actions');if(a)left.parentElement.insertBefore(c,a)}
function installPeopleNav(nav,internal){if(nav.querySelector('[data-business-module="people"]'))return;const group=document.createElement('div');group.className='nav-group';group.dataset.businessModule='people';group.innerHTML='<div class="nav-group-label business-nav-label"><span>PEOPLE</span><small>Operational</small></div><button class="nav-item" type="button" data-page="attendance" data-people-nav="1"><span>◷</span><b>Absensi</b></button><button class="nav-item" type="button" data-page="payroll" data-people-nav="1"><span>▤</span><b>Payroll</b></button>';const analytics=Array.from(nav.querySelectorAll('.nav-group')).find(g=>g.querySelector('[data-page="roadmap"]'));if(analytics)nav.insertBefore(group,analytics);else if(internal)nav.insertBefore(group,internal);else nav.appendChild(group);group.querySelectorAll('[data-people-nav]').forEach(btn=>{btn.addEventListener('click',()=>{window.showPage?.(btn.dataset.page);window.__nusantaraPeopleWorkspace?.show?.(btn.dataset.page)})})}
function installNav(){const nav=document.querySelector('.nav');if(!nav)return;const groups=Array.from(nav.querySelectorAll('.nav-group'));const operational=groups.find(g=>g.querySelector('[data-page="tagihan"]')),customers=groups.find(g=>g.querySelector('[data-page="pelanggan"]')),system=groups.find(g=>g.querySelector('[data-page="histori"]')),internal=groups.find(g=>g.querySelector('.nav-external'));if(operational?.querySelector('.nav-group-label'))operational.querySelector('.nav-group-label').textContent='WIFI';if(customers?.querySelector('.nav-group-label'))customers.querySelector('.nav-group-label').textContent='WIFI · PELANGGAN';if(system?.querySelector('.nav-group-label'))system.querySelector('.nav-group-label').textContent='SYSTEM';if(internal?.querySelector('.nav-group-label'))internal.querySelector('.nav-group-label').textContent='LEGACY';const txt=internal?.querySelector('.nav-external b');if(txt)txt.textContent='Absensi Legacy';installPeopleNav(nav,internal)}
function installDashboardContext(){const d=document.getElementById('page-dashboard');if(!d||d.querySelector('[data-business-shell-notice]'))return;const h=d.querySelector('.hero');if(h){const k=h.querySelector('.hero-kicker'),t=h.querySelector('h2'),p=h.querySelector('p');if(k)k.textContent='NUSANTARA BUSINESS · WIFI';if(t)t.innerHTML='Kelola operasional WiFi<br><span>dengan lebih tenang.</span>';if(p)p.textContent='Billing, pelanggan, pembayaran, dan analytics menjadi modul pertama dalam satu Business Portal Nusantara.'}const n=document.createElement('div');n.className='business-shell-notice';n.dataset.businessShellNotice='1';n.innerHTML='<div class="business-shell-notice-icon">NB</div><div><strong>Unified Business Portal</strong><span>WiFi dan People berjalan dalam satu frontend. Database dan backend production tetap terpisah.</span></div>';const stats=d.querySelector('.stats-grid');if(stats)d.insertBefore(n,stats)}
function install(){if(state.installed)return;loadCss();installBrand();installTopbarContext();installNav();installDashboardContext();state.installed=true;window[KEY]={installed:true,version:state.version}}window[KEY]={installed:false,version:state.version,install};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();